export * from '../API/certificates/types';
export * from '../API/experiences/types';
export * from '../API/works/types';
export * from '../API/general/types';
export * from '../API/testimonials/types';
export * from '../API/contact/types';
export * from '../API/resume/types';
export * from '../API/stack/types';
export * from '../API/skills/types'